apiVersion: v2
name: aztdp
description: Adaptive Zero-Trust Defense Platform
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - security
  - zero-trust
  - keycloak
  - opa
maintainers:
  - name: AZTDP
