server:
  port: 8082

aztdp:
  riskEngineUrl: ${AZTDP_RISK_ENGINE_URL:http://risk-engine:8080}
  policyGatewayUrl: ${AZTDP_POLICY_GATEWAY_URL:http://gateway:8080}
  tokenRevocationUrl: ${AZTDP_TOKEN_REVOKE_URL:http://gateway:8080/v1/tokens/revoke}
  trustedProxies: ${AZTDP_TRUSTED_PROXIES:}
  failOpen: ${AZTDP_FAIL_OPEN:false}
  internalToken: ${AZTDP_INTERNAL_TOKEN:}
  timeouts:
    connectMs: ${AZTDP_TIMEOUT_CONNECT_MS:200}
    readMs: ${AZTDP_TIMEOUT_READ_MS:800}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZTDP_OIDC_ISSUER:http://keycloak:8080/realms/aztdp}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      access: read_only
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
