import os

RISK_BASE = float(os.getenv("AZTDP_RISK_BASE", "0.1"))
RISK_SENSITIVITY_WEIGHT = float(os.getenv("AZTDP_RISK_SENSITIVITY_WEIGHT", "0.15"))
RISK_IP_DRIFT_WEIGHT = float(os.getenv("AZTDP_RISK_IP_DRIFT_WEIGHT", "0.35"))
RISK_UA_DRIFT_WEIGHT = float(os.getenv("AZTDP_RISK_UA_DRIFT_WEIGHT", "0.2"))
RISK_GEO_DRIFT_WEIGHT = float(os.getenv("AZTDP_RISK_GEO_DRIFT_WEIGHT", "0.2"))

REPLAY_WINDOW_SECONDS = int(os.getenv("AZTDP_REPLAY_WINDOW_SECONDS", "60"))
TOKEN_TTL_SECONDS = int(os.getenv("AZTDP_TOKEN_TTL_SECONDS", "1800"))

REDIS_URL = os.getenv("AZTDP_REDIS_URL", "")
ANOMALY_URL = os.getenv("AZTDP_ANOMALY_URL", "")
TELEMETRY_URL = os.getenv("AZTDP_TELEMETRY_URL", "")
